# Offense count: 15
# This cop supports safe autocorrection (--autocorrect).
Layout/ClosingHeredocIndentation:
  Exclude:
    - 'lib/puppet/provider/sqlserver.rb'
    - 'spec/acceptance/sqlserver_login_spec.rb'
    - 'spec/acceptance/sqlserver_user_spec.rb'
    - 'spec/acceptance/z_last_sqlserver_features_spec.rb'
    - 'spec/defines/database_spec.rb'
    - 'spec/defines/login/permissions_spec.rb'
    - 'spec/defines/login_spec.rb'
    - 'spec/defines/sp_configure_spec.rb'
    - 'spec/defines/user/permissions_spec.rb'
    - 'spec/defines/user_spec.rb'
    - 'spec/spec_helper_acceptance_local.rb'
    - 'spec/sql_testing_helpers.rb'

# Offense count: 33
# This cop supports safe autocorrection (--autocorrect).
Layout/EmptyLineAfterGuardClause:
  Enabled: false

# Offense count: 46
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowMultipleStyles, EnforcedHashRocketStyle, EnforcedColonStyle, EnforcedLastArgumentHashStyle.
# SupportedHashRocketStyles: key, separator, table
# SupportedColonStyles: key, separator, table
# SupportedLastArgumentHashStyles: always_inspect, always_ignore, ignore_implicit, ignore_explicit
Layout/HashAlignment:
  Exclude:
    - 'lib/puppet/provider/sqlserver.rb'
    - 'lib/puppet/provider/sqlserver_instance/mssql.rb'
    - 'lib/puppet_x/sqlserver/features.rb'
    - 'lib/puppet_x/sqlserver/sql_connection.rb'
    - 'spec/acceptance/sqlserver_config_spec.rb'
    - 'spec/defines/database_spec.rb'
    - 'spec/unit/puppet/provider/sqlserver_instance_spec.rb'

# Offense count: 4
# This cop supports safe autocorrection (--autocorrect).
Layout/HeredocIndentation:
  Exclude:
    - 'lib/puppet/property/sqlserver_tsql.rb'
    - 'lib/puppet/provider/sqlserver.rb'
    - 'spec/sql_testing_helpers.rb'
    - 'spec/unit/puppet/provider/sqlserver_tsql_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Layout/SpaceAroundMethodCallOperator:
  Exclude:
    - 'spec/acceptance/z_last_sqlserver_features_spec.rb'

# Offense count: 2
# Configuration parameters: AllowedMethods.
# AllowedMethods: enums
Lint/ConstantDefinitionInBlock:
  Exclude:
    - 'lib/puppet/provider/sqlserver_instance/mssql.rb'
    - 'spec/functions/sqlserver_upcase_spec.rb'

# Offense count: 3
# Configuration parameters: IgnoreLiteralBranches, IgnoreConstantBranches.
Lint/DuplicateBranch:
  Exclude:
    - 'spec/acceptance/sqlserver_login_spec.rb'
    - 'spec/spec_helper_acceptance_local.rb'
    - 'spec/sql_testing_helpers.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Lint/DuplicateRegexpCharacterClassElement:
  Exclude:
    - 'lib/puppet/type/sqlserver_tsql.rb'

# Offense count: 7
# Configuration parameters: AllowComments, AllowEmptyLambdas.
Lint/EmptyBlock:
  Exclude:
    - 'lib/puppet/type/sqlserver_instance.rb'
    - 'lib/puppet_x/sqlserver/features.rb'
    - 'spec/defines/manifest_shared_examples.rb'
    - 'spec/functions/functions_shared_examples.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: AllowComments.
Lint/EmptyConditionalBody:
  Exclude:
    - 'lib/puppet/parser/functions/sqlserver_validate_range.rb'

# Offense count: 10
# This cop supports unsafe autocorrection (--autocorrect-all).
Lint/OrAssignmentToConstant:
  Exclude:
    - 'lib/puppet_x/sqlserver/features.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
Lint/RedundantCopDisableDirective:
  Exclude:
    - 'lib/puppet_x/sqlserver/server_helper.rb'

# Offense count: 3
# Configuration parameters: AllowComments, AllowNil.
Lint/SuppressedException:
  Exclude:
    - 'lib/puppet_x/sqlserver/features.rb'
    - 'lib/puppet_x/sqlserver/sql_connection.rb'

# Offense count: 16
# Configuration parameters: AllowedMethods, AllowedPatterns, CountRepeatedAttributes.
Metrics/AbcSize:
  Max: 36

# Offense count: 6
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns, inherit_mode.
# AllowedMethods: refine
Metrics/BlockLength:
  Max: 177

# Offense count: 1
# Configuration parameters: CountComments, CountAsOne.
Metrics/ClassLength:
  Max: 158

# Offense count: 10
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Max: 12

# Offense count: 40
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 41

# Offense count: 10
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Max: 13

# Offense count: 12
# Configuration parameters: ForbiddenDelimiters.
# ForbiddenDelimiters: (?i-mx:(^|\s)(EO[A-Z]{1}|END)(\s|$))
Naming/HeredocDelimiterNaming:
  Exclude:
    - 'lib/puppet/type/sqlserver_tsql.rb'
    - 'spec/defines/database_spec.rb'
    - 'spec/defines/login/permissions_spec.rb'
    - 'spec/defines/login_spec.rb'
    - 'spec/defines/sp_configure_spec.rb'
    - 'spec/defines/user/permissions_spec.rb'
    - 'spec/defines/user_spec.rb'
    - 'spec/spec_helper_acceptance_local.rb'
    - 'spec/sql_testing_helpers.rb'

# Offense count: 2
# Configuration parameters: EnforcedStyle, CheckMethodNames, CheckSymbols, AllowedIdentifiers, AllowedPatterns.
# SupportedStyles: snake_case, normalcase, non_integer
# AllowedIdentifiers: capture3, iso8601, rfc1123_date, rfc822, rfc2822, rfc3339, x86_64
Naming/VariableNumber:
  Exclude:
    - 'lib/puppet/provider/sqlserver_features/mssql.rb'
    - 'lib/puppet/provider/sqlserver_instance/mssql.rb'

# Offense count: 2
# This cop supports unsafe autocorrection (--autocorrect-all).
Performance/InefficientHashSearch:
  Exclude:
    - 'spec/spec_helper_acceptance_local.rb'
    - 'spec/sql_testing_helpers.rb'

# Offense count: 2
# This cop supports unsafe autocorrection (--autocorrect-all).
Performance/StringInclude:
  Exclude:
    - 'lib/puppet/parser/functions/sqlserver_validate_size.rb'
    - 'lib/puppet/provider/sqlserver_tsql/mssql.rb'

# Offense count: 66
# Configuration parameters: Prefixes, AllowedPatterns.
# Prefixes: when, with, without
RSpec/ContextWording:
  Enabled: false

# Offense count: 28
# Configuration parameters: IgnoredMetadata.
RSpec/DescribeClass:
  Enabled: false

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
RSpec/EmptyHook:
  Exclude:
    - 'spec/acceptance/sqlserver_user_spec.rb'

# Offense count: 7
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowConsecutiveOneLiners.
RSpec/EmptyLineAfterExample:
  Exclude:
    - 'spec/acceptance/sqlserver_instance_spec.rb'
    - 'spec/acceptance/sqlserver_login_spec.rb'
    - 'spec/functions/sqlserver_upcase_spec.rb'
    - 'spec/unit/puppet/property/tsql_spec.rb'
    - 'spec/unit/puppet_x/sql_connection_spec.rb'

# Offense count: 56
# This cop supports safe autocorrection (--autocorrect).
RSpec/EmptyLineAfterExampleGroup:
  Exclude:
    - 'spec/defines/database_spec.rb'
    - 'spec/defines/login/permissions_spec.rb'
    - 'spec/defines/login_spec.rb'
    - 'spec/defines/role/permissions_spec.rb'
    - 'spec/defines/role_spec.rb'
    - 'spec/defines/user/permissions_spec.rb'
    - 'spec/defines/user_spec.rb'
    - 'spec/functions/sqlserver_validate_size_spec.rb'
    - 'spec/unit/puppet/provider/sqlserver_tsql_spec.rb'
    - 'spec/unit/puppet_x/sql_connection_spec.rb'

# Offense count: 6
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowConsecutiveOneLiners.
RSpec/EmptyLineAfterHook:
  Exclude:
    - 'spec/acceptance/sqlserver_login_spec.rb'
    - 'spec/acceptance/sqlserver_role_spec.rb'
    - 'spec/acceptance/sqlserver_user_spec.rb'
    - 'spec/unit/puppet/provider/sqlserver_features_spec.rb'
    - 'spec/unit/puppet_x/sql_connection_spec.rb'

# Offense count: 51
# Configuration parameters: CountAsOne.
RSpec/ExampleLength:
  Max: 59

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
RSpec/ExcessiveDocstringSpacing:
  Exclude:
    - 'spec/defines/user/permissions_spec.rb'

# Offense count: 2
# Configuration parameters: Include, CustomTransform, IgnoreMethods, SpecSuffixOnly.
# Include: **/*_spec*rb*, **/spec/**/*
RSpec/FilePath:
  Exclude:
    - 'spec/unit/puppet_x/server_helper_spec.rb'
    - 'spec/unit/puppet_x/sql_connection_spec.rb'

# Offense count: 23
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: single_line_only, single_statement_only, disallow, require_implicit
RSpec/ImplicitSubject:
  Exclude:
    - 'spec/defines/config_spec.rb'
    - 'spec/defines/database_spec.rb'
    - 'spec/defines/login_spec.rb'
    - 'spec/defines/manifest_shared_examples.rb'
    - 'spec/defines/role/permissions_spec.rb'
    - 'spec/defines/role_spec.rb'
    - 'spec/defines/sp_configure_spec.rb'
    - 'spec/defines/user_spec.rb'

# Offense count: 302
# Configuration parameters: AssignmentOnly.
RSpec/InstanceVariable:
  Exclude:
    - 'spec/acceptance/sqlserver_config_spec.rb'
    - 'spec/acceptance/sqlserver_database_spec.rb'
    - 'spec/acceptance/sqlserver_instance_spec.rb'
    - 'spec/acceptance/sqlserver_login_spec.rb'
    - 'spec/acceptance/sqlserver_role_spec.rb'
    - 'spec/acceptance/sqlserver_tsql_spec.rb'
    - 'spec/acceptance/sqlserver_user_spec.rb'
    - 'spec/unit/puppet/property/tsql_spec.rb'
    - 'spec/unit/puppet/provider/sqlserver_features_spec.rb'
    - 'spec/unit/puppet/provider/sqlserver_instance_spec.rb'
    - 'spec/unit/puppet/provider/sqlserver_tsql_spec.rb'
    - 'spec/unit/puppet/type/sqlserver_instance_spec.rb'
    - 'spec/unit/puppet_x/sql_connection_spec.rb'

# Offense count: 1
RSpec/LeakyConstantDeclaration:
  Exclude:
    - 'spec/functions/sqlserver_upcase_spec.rb'

# Offense count: 6
RSpec/MultipleExpectations:
  Max: 8

# Offense count: 10
# Configuration parameters: AllowSubject.
RSpec/MultipleMemoizedHelpers:
  Max: 10

# Offense count: 17
# Configuration parameters: EnforcedStyle, IgnoreSharedExamples.
# SupportedStyles: always, named_only
RSpec/NamedSubject:
  Exclude:
    - 'spec/unit/puppet_x/sql_connection_spec.rb'

# Offense count: 31
# Configuration parameters: AllowedGroups.
RSpec/NestedGroups:
  Max: 4

# Offense count: 70
# Configuration parameters: AllowedPatterns.
# AllowedPatterns: ^expect_, ^assert_
RSpec/NoExpectationExample:
  Exclude:
    - 'spec/acceptance/sqlserver_config_spec.rb'
    - 'spec/acceptance/sqlserver_database_spec.rb'
    - 'spec/acceptance/sqlserver_instance_spec.rb'
    - 'spec/acceptance/sqlserver_login_spec.rb'
    - 'spec/acceptance/sqlserver_role_spec.rb'
    - 'spec/acceptance/sqlserver_tsql_spec.rb'
    - 'spec/acceptance/sqlserver_user_spec.rb'
    - 'spec/acceptance/z_last_sqlserver_features_spec.rb'
    - 'spec/functions/sqlserver_upcase_spec.rb'
    - 'spec/functions/sqlserver_validate_size_spec.rb'
    - 'spec/unit/puppet/provider/sqlserver_features_spec.rb'
    - 'spec/unit/puppet/provider/sqlserver_instance_spec.rb'
    - 'spec/unit/puppet/provider/sqlserver_tsql_spec.rb'
    - 'spec/unit/puppet/type/sqlserver_instance_spec.rb'
    - 'spec/unit/puppet_x/server_helper_spec.rb'

# Offense count: 5
# This cop supports safe autocorrection (--autocorrect).
RSpec/ReceiveNever:
  Exclude:
    - 'spec/unit/puppet_x/sql_connection_spec.rb'

# Offense count: 4
RSpec/RepeatedExampleGroupBody:
  Exclude:
    - 'spec/defines/login/permissions_spec.rb'
    - 'spec/defines/user/permissions_spec.rb'

# Offense count: 4
RSpec/RepeatedExampleGroupDescription:
  Exclude:
    - 'spec/defines/config_spec.rb'
    - 'spec/unit/puppet/provider/sqlserver_features_spec.rb'

# Offense count: 7
RSpec/StubbedMock:
  Exclude:
    - 'spec/unit/puppet/provider/sqlserver_features_spec.rb'
    - 'spec/unit/puppet/provider/sqlserver_instance_spec.rb'
    - 'spec/unit/puppet/provider/sqlserver_tsql_spec.rb'
    - 'spec/unit/puppet_x/sql_connection_spec.rb'

# Offense count: 2
RSpec/SubjectDeclaration:
  Exclude:
    - 'spec/unit/puppet_x/server_helper_spec.rb'
    - 'spec/unit/puppet_x/sql_connection_spec.rb'

# Offense count: 6
RSpec/SubjectStub:
  Exclude:
    - 'spec/unit/puppet_x/server_helper_spec.rb'
    - 'spec/unit/puppet_x/sql_connection_spec.rb'

# Offense count: 4
RSpec/UnspecifiedException:
  Exclude:
    - 'spec/functions/sqlserver_validate_hash_uniq_values_spec.rb'
    - 'spec/functions/sqlserver_validate_instance_name_spec.rb'

# Offense count: 2
# Configuration parameters: IgnoreNameless, IgnoreSymbolicNames.
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/unit/puppet_x/sql_connection_spec.rb'

# Offense count: 7
Security/Open:
  Exclude:
    - 'lib/puppet_x/sqlserver/features.rb'
    - 'lib/puppet_x/sqlserver/sql_connection.rb'

# Offense count: 4
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowedVars.
Style/FetchEnvVar:
  Exclude:
    - 'lib/puppet/provider/sqlserver.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowSplatArgument.
Style/HashConversion:
  Exclude:
    - 'lib/puppet_x/sqlserver/features.rb'

# Offense count: 30
# This cop supports safe autocorrection (--autocorrect).
Style/IfUnlessModifier:
  Exclude:
    - 'lib/puppet/parser/functions/sqlserver_is_domain_or_local_user.rb'
    - 'lib/puppet/parser/functions/sqlserver_validate_instance_name.rb'
    - 'lib/puppet/parser/functions/sqlserver_validate_range.rb'
    - 'lib/puppet/parser/functions/sqlserver_validate_size.rb'
    - 'lib/puppet/property/sqlserver_login.rb'
    - 'lib/puppet/provider/sqlserver_features/mssql.rb'
    - 'lib/puppet/provider/sqlserver_instance/mssql.rb'
    - 'lib/puppet/provider/sqlserver_tsql/mssql.rb'
    - 'lib/puppet/type/sqlserver_instance.rb'
    - 'lib/puppet/type/sqlserver_tsql.rb'
    - 'lib/puppet_x/sqlserver/sql_connection.rb'
    - 'spec/spec_helper_acceptance_local.rb'
    - 'spec/sql_testing_helpers.rb'
    - 'spec/unit/puppet/provider/sqlserver_features_spec.rb'
    - 'spec/unit/puppet/sqlserver_spec_helper.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: AllowedMethods.
# AllowedMethods: nonzero?
Style/IfWithBooleanLiteralBranches:
  Exclude:
    - 'lib/puppet_x/sqlserver/server_helper.rb'

# Offense count: 1
Style/MixinUsage:
  Exclude:
    - 'spec/spec_helper.rb'

# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: EnforcedStyle, AllowedMethods, AllowedPatterns.
# SupportedStyles: predicate, comparison
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
    - 'lib/puppet/type/sqlserver_instance.rb'

# Offense count: 3
# Configuration parameters: AllowedMethods.
# AllowedMethods: respond_to_missing?
Style/OptionalBooleanParameter:
  Exclude:
    - 'lib/puppet/provider/sqlserver_instance/mssql.rb'
    - 'lib/puppet/type/sqlserver_tsql.rb'
    - 'spec/defines/manifest_shared_examples.rb'

# Offense count: 28
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantRegexpEscape:
  Exclude:
    - 'lib/puppet/parser/functions/sqlserver_validate_instance_name.rb'
    - 'lib/puppet/type/sqlserver_instance.rb'
    - 'spec/defines/database_spec.rb'
    - 'spec/unit/puppet/property/tsql_spec.rb'

# Offense count: 2
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantSelfAssignmentBranch:
  Exclude:
    - 'spec/acceptance/sqlserver_instance_spec.rb'
    - 'spec/acceptance/z_last_sqlserver_features_spec.rb'

# Offense count: 16
# This cop supports safe autocorrection (--autocorrect).
Style/RedundantStringEscape:
  Exclude:
    - 'spec/spec_helper_acceptance_local.rb'
    - 'spec/sql_testing_helpers.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  Exclude:
    - 'spec/defines/user_spec.rb'

# Offense count: 3
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle.
# SupportedStyles: implicit, explicit
Style/RescueStandardError:
  Exclude:
    - 'lib/puppet_x/sqlserver/features.rb'
    - 'spec/spec_helper.rb'

# Offense count: 3
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowModifier.
Style/SoleNestedConditional:
  Exclude:
    - 'lib/puppet/parser/functions/sqlserver_validate_size.rb'
    - 'lib/puppet/provider/sqlserver.rb'
    - 'spec/spec_helper_acceptance_local.rb'

# Offense count: 34
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: Mode.
Style/StringConcatenation:
  Exclude:
    - 'spec/acceptance/sqlserver_config_spec.rb'
    - 'spec/acceptance/sqlserver_database_spec.rb'
    - 'spec/acceptance/sqlserver_instance_spec.rb'
    - 'spec/acceptance/sqlserver_login_spec.rb'
    - 'spec/acceptance/sqlserver_role_spec.rb'
    - 'spec/acceptance/sqlserver_tsql_spec.rb'
    - 'spec/acceptance/sqlserver_user_spec.rb'
    - 'spec/unit/puppet/provider/sqlserver_instance_spec.rb'

# Offense count: 1
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyle, AllowSafeAssignment.
# SupportedStyles: require_parentheses, require_no_parentheses, require_parentheses_when_complex
Style/TernaryParentheses:
  Exclude:
    - 'lib/puppet/parser/functions/sqlserver_validate_hash_uniq_values.rb'

# Offense count: 88
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: EnforcedStyleForMultiline.
# SupportedStylesForMultiline: comma, consistent_comma, no_comma
Style/TrailingCommaInHashLiteral:
  Enabled: false
